### PR TITLE
implemented cache configuration

### PR DESCRIPTION
**Pull request by mcrauwel**

### CODE REVIEW

**Comment by juliangut** [comment]
Sorry, I was on holidays

Have you seen that PHPMD is complaining about [CBO](http://pdepend.org/documentation/software-metrics/coupling-between-objects.html)?
.../slim-doctrine-middleware/src/DoctrineMiddleware.php:20  The class DoctrineMiddleware has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.

Any idea on how to solve this?

_Additionally_

``` php
        $proxyDir = null;
        if ($this->hasOption('proxy_path')) {
            $proxyDir = $this->getOption('proxy_path');
        }
```

can be reduced and expressed directly as

``` php
$proxyDir = $this->getOption('proxy_path');
```

**Comment by mcrauwel** [comment]
I saw the error, but I don't really know how I should fix it ;)

**Comment by mgersten** [comment]
Perhaps the cache could be its own class (e.g. DoctrineMiddlewareCache) that's instantiated and called in setup.  That should solve the coupling issue.

**Comment by mcrauwel** [comment]
@mgersten shouldn't it be more like a DoctrineMiddlewareCacheFactory that instantiates a CacheProvider object which we can use in the Setup::createConfiguration() call...

**Comment by juliangut** [comment]
This is definitively better, thanks for your work, merging!

**Pull request merged**
